import { ORIGIN } from '../src/site.mjs';
export const escape = value => String(value).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
export function metadata({path,title,description,school=false,image,course,noindex=false}) {
  const url=ORIGIN+path, name=school?'SozoRockSchool':'SozoRock Technology';
  const share=image||'/assets/social/'+(school?'school':'corporate')+'-v1.png';
  const company={'@type':'Organization','@id':ORIGIN+'/#organization',name:'SozoRock Technology',legalName:'SozoRock Tech Inc.',url:ORIGIN+'/',logo:ORIGIN+'/favicon.svg'};
  const provider=school?{'@id':ORIGIN+'/school#school'}:{'@id':company['@id']};
  const graph=[company];
  if(school)graph.push({'@type':'EducationalOrganization','@id':ORIGIN+'/school#school',name:'SozoRockSchool',url:ORIGIN+'/school',parentOrganization:{'@id':company['@id']}});
  graph.push({'@type':'WebSite','@id':ORIGIN+'/#website',name:'SozoRock Technology',url:ORIGIN+'/',publisher:{'@id':company['@id']},inLanguage:'en-US'},
    {'@type':path.startsWith('/work/')?'CreativeWork':path.endsWith('/contact')?'ContactPage':'WebPage','@id':url+'#page',url,name:title,description,isPartOf:{'@id':ORIGIN+'/#website'},publisher:provider,inLanguage:'en-US'});
  if(course)graph.push({'@type':'Course','@id':url+'#course',url,name:course[2],description:course[5],provider,timeRequired:'P12W',inLanguage:'en-US'});
  if(path!=='/')graph.push({'@type':'BreadcrumbList',itemListElement:[{name:'SozoRock Technology',item:ORIGIN+'/'},...(school&&path!=='/school'?[{name:'School',item:ORIGIN+'/school'}]:[]),{name:title.split(' | ')[0],item:url}].map((x,i)=>({'@type':'ListItem',position:i+1,...x}))});
  return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow,max-image-preview:large'}"><link rel="canonical" href="${url}"><meta property="og:type" content="${path.startsWith('/work/')?'article':'website'}"><meta property="og:site_name" content="${name}"><meta property="og:locale" content="en_US"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${ORIGIN+share}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${escape(title)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(title)}"><meta name="twitter:description" content="${escape(description)}"><meta name="twitter:image" content="${ORIGIN+share}"><meta name="twitter:image:alt" content="${escape(title)}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="icon" href="/favicon-48.png" sizes="48x48"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script>`;
}
