export const cbcapPreview = `<section class="cbcap-stage" data-cbcap aria-labelledby="cbcap-stage-title">
  <div class="stage-heading"><div><p class="label">Experience CB-CAP</p><h2 id="cbcap-stage-title">Start with a place.<br>Stay with the evidence.</h2></div><p class="edition">CDC PLACES<br>2025 release</p></div>
  <div class="stage-tools" data-tools hidden><label>State<select data-state aria-label="State"></select></label><label>County<select data-county aria-label="County"></select></label><label>Measure<select data-measure aria-label="Measure"><option value="transport">Transportation barriers</option><option value="uninsured">Adults without health insurance</option><option value="diabetes">Diagnosed diabetes</option></select></label></div>
  <div class="step-nav" aria-label="Evidence view" data-steps hidden><button type="button" data-step="explore" aria-pressed="true">01 Explore</button><button type="button" data-step="compare" aria-pressed="false">02 Compare</button><button type="button" data-step="trace" aria-pressed="false">03 Trace the source</button></div>
  <div class="cbcap-result" data-result aria-live="polite"><div class="reading"><div><p class="place-label">Albany County, New York</p><p class="number">7.2<small>%</small></p><p class="ci">95% confidence interval: 6.1% to 8.5%</p></div><div><h3>Transportation barriers</h3><p>Adults aged 18 and older</p><p>County FIPS 36001 · Model-based estimate</p></div></div></div>
  <p class="data-status" data-status>Enable JavaScript to explore other counties and compare estimates.</p>
  <div class="stage-caption"><p>Source snapshot: July 14, 2026</p><p>County estimates. Not individual assessments.</p></div>
  <details class="source-fallback"><summary>Source and measurement limits</summary><p><a href="https://data.cdc.gov/500-Cities-Places/PLACES-County-Data-GIS-Friendly-Format-2025-releas/i46a-9kgh">CDC PLACES, 2025 county release</a>, released December 4, 2025. Underlying source years: BRFSS 2023/2022; Census 2023; ACS 2019 to 2023/2018 to 2022. This is a published data snapshot, not a live feed. Estimates describe county populations, not individual diagnoses or current service counts. Missing data is not zero. Differences do not establish statistical significance or causation.</p></details>
</section>`;
