import { cbcapPreview } from './cbcap-preview.mjs';
import { policies } from './corporate-policies.mjs';

export const link = (href, text) => `<a class="text-link" href="${href}">${text}</a>`;
export const nav = `<header class="corporate-header"><a class="corporate-mark" href="/" aria-label="SozoRock Technology"><span>SozoRock<strong>Technology</strong></span></a><nav id="corporate-nav" aria-label="Primary"><a href="/cb-cap">CB-CAP</a><a href="/what-we-do">What we do</a><a href="/school">School</a><a href="/insights">Insights</a><a href="/about">About</a><a href="/contact">Talk to us</a></nav><button class="corporate-menu" aria-controls="corporate-nav" aria-expanded="false" hidden>Menu</button></header><noscript><style>@media(max-width:800px){.corporate-header nav{display:flex}}</style></noscript>`;
export const footer = `<footer class="corporate-footer"><div class="footer-top"><a class="footer-name" href="/">SozoRock<br>Technology</a><div><p>Technology for<br>complex operations.</p>${link('/contact', 'Talk to us')}</div></div><nav aria-label="Footer"><a href="/cb-cap">CB-CAP</a><a href="/what-we-do">What we do</a><a href="/school">School</a><a href="/insights">Insights</a><a href="/about">About</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/accessibility">Accessibility</a><a href="/legal">Legal</a></nav><p class="copyright">© ${new Date().getFullYear()} SozoRock Tech Inc. All rights reserved.</p></footer>`;
const action = (href, text) => `<a class="action" href="${href}">${text}</a>`;
const contactEnd = `<section class="contact-ending"><h2>What needs<br>to work better?</h2><div><p>Start with your operation, the people it serves and the decisions that need to improve.</p>${link('/contact', 'Talk to us')}</div></section>`;
const productScripts = '<script src="/cbcap-preview.js" defer></script>';
const formScripts = '<script src="/engagement-config.js"></script><script src="/contact.js" defer></script>';
const capabilities = [
  ['ai-intelligent-systems', 'AI &amp; Intelligent Systems', 'Put intelligence into the work.', 'Design AI around a defined task, the evidence it can use and the decisions that remain with people. Connect models, tools and evaluation to the operation they need to support.', 'Workflow design, retrieval, model evaluation and human review.'],
  ['data-decision-infrastructure', 'Data &amp; Decision Infrastructure', 'Make information usable.', 'Connect fragmented sources to a shared question. Preserve definitions, geography, dates and uncertainty as data moves from ingestion to the point of decision.', 'Data pipelines, source contracts, evidence products and decision interfaces.'],
  ['cybersecurity-identity', 'Cybersecurity &amp; Identity', 'Design trust into access.', 'Define who can do what, under which conditions, and how those decisions are reviewed. Bring identity, permissions and operational controls into the design from the start.', 'Identity architecture, access governance, security controls and assurance evidence.'],
  ['product-engineering', 'Product Engineering', 'Carry the idea into operation.', 'Connect product strategy and interaction design to the systems behind the experience. Build for accessible use, reliable delivery and the ability to recover when something goes wrong.', 'Product design, application engineering, cloud architecture and controlled releases.']
];
const capabilityRows = capabilities.map(([slug, name, , description], i) => `<section class="capability-row"><p class="row-index">0${i + 1}</p><h2>${name}</h2><div><p>${description}</p>${link('/what-we-do/' + slug, 'Explore the capability')}</div></section>`).join('');
export const pages = {
  ...policies,
  '/': {
    title: 'SozoRock Technology | Technology for Complex Operations',
    description: 'AI, data, cybersecurity and product engineering for complex operations. Discover CB-CAP county intelligence and applied learning at SozoRockSchool.',
    body: `<section class="corporate-hero"><p class="label">SozoRock Technology</p><h1>Technology for<br>complex operations.</h1><div class="hero-bottom"><p>AI, data, cybersecurity and product engineering.<br>Built around the work your organization needs to do.</p>${action('/cb-cap', 'Explore CB-CAP')}</div></section><section class="product-feature"><div class="product-heading"><p class="label">Our flagship product</p><p class="product-name">CB-CAP</p></div><div><h2>County intelligence,<br>with the evidence attached.</h2><p>Understand county conditions. Compare the context. Follow every estimate back to its source.</p>${link('/cb-cap', 'Discover CB-CAP')}</div></section>${cbcapPreview}<section class="section-intro"><p class="label">What we do</p><h2>Connect the disciplines.<br>Move the work forward.</h2></section>${capabilityRows}<section class="school-feature"><div><p class="label">SozoRockSchool</p><h2>Learn through<br>the work.</h2><p>Four focused AI and cybersecurity programs. Twelve weeks, delivered virtually, with guided practice, an applied project and human assessment.</p><p>Applied learning by SozoRock Technology.</p>${link('/school', 'Explore School')}</div><picture><source media="(max-width:768px)" srcset="/assets/open-school-us-mobile.webp"><img src="/assets/open-school-us-wide.webp" width="1916" height="821" loading="lazy" alt="SozoRockSchool sculpture with four entrances, representing virtual learning"></picture></section><section class="insight-feature"><p class="label">Our thinking</p><div><h2>Evidence needs<br>its context.</h2><p>A number becomes more useful when its geography, population and limitations travel with it.</p>${link('/insights/evidence-needs-context', 'Read the perspective')}</div></section>${contactEnd}`,
    scripts: productScripts
  },
  '/cb-cap': {
    title: 'CB-CAP | County Intelligence | SozoRock Technology',
    description: 'Explore CB-CAP, a SozoRock Technology product. Understand county conditions, compare estimates and trace geography, population, uncertainty and sources.',
    body: `<section class="product-hero"><p class="label">CB-CAP / A SozoRock Technology product</p><h1>County intelligence,<br>with the evidence<br><em>attached.</em></h1><div class="hero-bottom"><p>Understand county conditions. Compare the context.<br>Follow every estimate back to its source.</p>${action('/cb-cap/request-demo', 'Request a demo')}</div></section>${cbcapPreview}<section class="section-intro"><p class="label">From exploration to discussion</p><h2>Make the evidence<br>part of the conversation.</h2></section><section class="capability-row"><p class="row-index">01</p><h2>Resolve<br>the geography.</h2><div><p>Select a state and county. Keep the county identifier attached to the result so a place name never implies more precision than the data supports.</p></div></section><section class="capability-row"><p class="row-index">02</p><h2>Compare<br>the context.</h2><div><p>Explore the same measure across two counties within a state. Read the population definition and confidence interval alongside each estimate.</p><p>Differences invite further investigation. They do not establish causation or statistical significance.</p></div></section><section class="capability-row"><p class="row-index">03</p><h2>Inspect<br>the evidence.</h2><div><p>Open the source record without leaving the question behind. Review the dataset, release date, underlying years, geography and interpretation limits.</p><p>This public experience uses a published CDC PLACES snapshot. Institutional access and additional workflows are discussed separately and are not provided by this preview.</p></div></section><section class="contact-ending"><h2>What does the evidence<br>mean for your work?</h2><div><p>Explore CB-CAP with your team’s geography, planning questions and evidence requirements in view.</p>${link('/cb-cap/request-demo', 'Request a demo')}</div></section>`,
    scripts: productScripts
  },
  '/cb-cap/request-demo': {
    title: 'Request a CB-CAP Demo | SozoRock Technology',
    description: 'Tell SozoRock Technology about your organization, geography and evidence requirements to discuss a CB-CAP product demonstration.',
    body: `<section class="page-intro"><p class="label">CB-CAP</p><h1>See it in the context<br>of your work.</h1><p class="lead">Tell us which geography you work with, the questions your team needs to answer and what you would like to explore.</p></section><section class="contact-layout"><div><h2>Request a demo</h2><p>Include your organization and the county or region relevant to your work. Our team will review your request and discuss the next step.</p><p>Please use business context only. Do not include personal health records or other sensitive information.</p></div><div data-contact-root data-context="corporate" data-product="cb-cap"><p>Enable JavaScript to send a demo enquiry. A request does not reserve a meeting time.</p></div></section>`,
    scripts: formScripts
  },
  '/what-we-do': {title: 'What We Do | SozoRock Technology', description: 'AI and intelligent systems, data and decision infrastructure, cybersecurity and identity, and product engineering for complex operations.', body: `<section class="page-intro"><p class="label">What we do</p><h1>Connect the disciplines.<br>Move the work forward.</h1><p class="lead">Complex operations depend on more than one system. We bring intelligence, data, security and product engineering into the same conversation.</p></section>${capabilityRows}${contactEnd}`},
  '/about': {title: 'About | SozoRock Technology', description: 'SozoRock Technology brings AI, data, cybersecurity and product engineering to complex operations. Meet our product and applied learning activities.', body: `<section class="page-intro"><p class="label">About SozoRock</p><h1>Built around<br>the work.</h1><p class="lead">SozoRock Technology is a commercial technology business focused on AI, data, cybersecurity, product engineering and complex operations.</p></section><article class="editorial-body"><h2>Technology with an operational purpose</h2><p>We begin with the people using a system, the decisions it needs to support and the conditions in which it must work. Product design, engineering, data and access controls belong in that same conversation.</p><h2>Our flagship product</h2><p>CB-CAP is a SozoRock Technology product for county intelligence and evidence exploration. Its product experience keeps geography, populations, sources and measurement limits visible.</p>${link('/cb-cap', 'Discover CB-CAP')}<h2>Applied learning</h2><p>SozoRockSchool offers four focused AI and cybersecurity programs, delivered virtually over twelve weeks. Guided practice, an applied project and human assessment connect learning to practical work.</p>${link('/school', 'Explore School')}<h2>Corporate identity</h2><p>SozoRock Technology is the public corporate brand of SozoRock Tech Inc., New York. Corporate and website responsibilities are described in our legal information.</p>${link('/legal', 'Legal information')}</article>${contactEnd}`},
  '/insights': {title: 'Insights | SozoRock Technology', description: 'Perspectives on evidence, product design and the systems behind complex operations from SozoRock Technology.', body: `<section class="page-intro"><p class="label">Insights</p><h1>Think through<br>the work.</h1><p class="lead">Perspectives on the decisions behind useful technology.</p></section><section class="insight-feature"><p class="label">Perspective / Data</p><div><h2>Evidence needs<br>its context.</h2><p>Geography, population, source dates and uncertainty belong beside the number, wherever it travels.</p>${link('/insights/evidence-needs-context', 'Read the perspective')}</div></section>${contactEnd}`},
  '/insights/evidence-needs-context': {title: 'Evidence Needs Its Context | SozoRock Technology', description: 'Why geography, population, source dates and uncertainty belong beside an estimate in a decision interface.', body: `<section class="page-intro"><p class="label">Perspective / Data / September 9, 2026</p><h1>Evidence needs<br>its context.</h1><p class="lead">A number should not lose its meaning on the way to a decision.</p></section><article class="editorial-body"><h2>Start with what was measured</h2><p>A county estimate describes a defined population in a defined place. It cannot become a neighborhood measurement simply because a user searched for a neighborhood. The interface needs to preserve the measurement geography.</p><h2>Keep time in view</h2><p>A dataset’s release date and the years underlying its measurements answer different questions. Display both. A recently published release may incorporate observations from earlier years.</p><h2>Carry uncertainty into comparisons</h2><p>Point estimates can look more decisive than the evidence permits. Display confidence intervals alongside the values. A difference between two estimates is not, by itself, a test of statistical significance or evidence of causation.</p><h2>Make inspection part of the experience</h2><p>In the CB-CAP public preview, a reader can select a county, compare the same measure within a state and trace the selected estimate to its source context. Missing values remain unavailable rather than becoming zero.</p>${link('/cb-cap', 'Explore CB-CAP')}<h2>Source</h2><p>The preview uses <a href="https://data.cdc.gov/500-Cities-Places/PLACES-County-Data-GIS-Friendly-Format-2025-releas/i46a-9kgh">CDC PLACES county data, 2025 release</a>. Read the dataset’s methods and measure definitions before interpreting a result.</p></article>`},
  '/contact': {title: 'Contact | SozoRock Technology', description: 'Discuss AI, data, cybersecurity and product engineering with SozoRock Technology. Contact our team about your operation and requirements.', body: `<section class="page-intro"><p class="label">Talk to us</p><h1>What needs<br>to work better?</h1><p class="lead">Describe the operation, who it serves and the decisions or systems you want to improve.</p></section><section class="contact-layout"><div><h2>Start a conversation</h2><p>Share your organization and the context for your enquiry.</p><p>For CB-CAP, ${link('/cb-cap/request-demo', 'request a demo')}. For programs and applications, use ${link('/school/contact', 'School contact')}.</p><p>Do not send identity documents, health information, passwords or payment details.</p></div><div data-contact-root data-context="corporate"><p>Enable JavaScript to use the online enquiry form. Your details are sent only when you choose Send enquiry.</p></div></section>`, scripts: formScripts}
};
for (const [slug, name, heading, description, scope] of capabilities) {
  pages['/what-we-do/' + slug] = {title: name.replaceAll('&amp;', '&') + ' | SozoRock Technology', description, body: `<section class="page-intro"><p class="label">What we do / ${name}</p><h1>${heading}</h1><p class="lead">${description}</p></section><article class="editorial-body"><h2>Shape the work together</h2><p>${scope}</p><p>We start with the current operation, the people involved and the constraints that matter. From there, we define the product or system, how it will be evaluated and what a useful result looks like.</p><h2>Connect design and delivery</h2><p>Make the user experience, data requirements, access boundaries and release process part of one implementation plan. Review the work against the task it needs to support.</p>${link('/contact', 'Discuss your requirements')}</article>${contactEnd}`};
}
