import React,{useEffect,useId,useState} from 'react';
import {countySource,countyMeasures,validateCountySnapshot} from './county-evidence.mjs';
const initialCounty={"fips": "36001", "state": "New York", "stateCode": "NY", "county": "Albany County", "transport": [7.2, 6.1, 8.5], "uninsured": [5.5, 4.2, 7], "diabetes": [9.2, 7.9, 10.7]};
export default function CountyEvidence(){
  const id=useId(),[rows,setRows]=useState(null),[error,setError]=useState(false),[attempt,setAttempt]=useState(0),[state,setState]=useState('New York'),[fips,setFips]=useState('36001'),[measure,setMeasure]=useState('transport');
  useEffect(()=>{const controller=new AbortController();let active=true;const timer=setTimeout(()=>controller.abort(),15000);setError(false);fetch(new URL(/* @vite-ignore */ '../data/cbcap-counties-2025.json',import.meta.url),{signal:controller.signal,credentials:'omit'}).then(r=>{if(!r.ok)throw Error('Unavailable');return r.json()}).then(validateCountySnapshot).then(data=>{if(active)setRows(data)}).catch(()=>{if(active)setError(true)}).finally(()=>clearTimeout(timer));return()=>{active=false;clearTimeout(timer);controller.abort()};},[attempt]);
  const county=rows?.find(r=>r.fips===fips)||initialCounty,d=county[measure],states=rows?[...new Set(rows.map(r=>r.state))].sort():[],counties=rows?.filter(r=>r.state===state).sort((a,b)=>a.county.localeCompare(b.county))||[];
  return <section className="county-evidence" aria-labelledby={`${id}-title`}><p className="eyebrow">PUBLISHED COUNTY EVIDENCE</p><h2 id={`${id}-title`}>Check the local context.</h2><p>Explore three population estimates before defining a service question. Keep county evidence separate from the sample ZIP-area scenarios.</p>
    {rows&&<div className="county-fields"><div className="county-field"><label htmlFor={`${id}-state`}>State</label><select id={`${id}-state`} value={state} onChange={e=>{setState(e.target.value);setFips(rows.filter(r=>r.state===e.target.value).sort((a,b)=>a.county.localeCompare(b.county))[0].fips)}}>{states.map(s=><option key={s}>{s}</option>)}</select></div><div className="county-field"><label htmlFor={`${id}-county`}>County</label><select id={`${id}-county`} value={fips} onChange={e=>setFips(e.target.value)}>{counties.map(c=><option key={c.fips} value={c.fips}>{c.county}</option>)}</select></div><div className="county-field"><label htmlFor={`${id}-measure`}>Population measure</label><select id={`${id}-measure`} value={measure} onChange={e=>setMeasure(e.target.value)}>{Object.entries(countyMeasures).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div></div>}
    <div className="county-reading" aria-live="polite"><h3>{county.county}, {county.state}</h3><p className="county-value">{d[0]===null?'Estimate unavailable':`${d[0].toFixed(1)}%`}</p><p>{countyMeasures[measure]} · {measure==='uninsured'?'Adults aged 18–64':'Adults aged 18 and older'}</p><p>{d[0]===null?'Missing data is not zero.':`95% confidence interval: ${d[1].toFixed(1)}%–${d[2].toFixed(1)}%.`} County FIPS {county.fips}.</p></div>
    {!rows&&(error?<p role="alert">County selection could not load. The Albany County transportation snapshot remains available. <button className="text-link" onClick={()=>setAttempt(attempt+1)}>Retry county selection</button></p>:<p role="status">Loading county selection…</p>)}
    <p className="county-source">Source: <a href={countySource.url}>{countySource.publisher}, {countySource.release}</a>, released {countySource.released}. Published snapshot: {countySource.snapshot}. Underlying years: {countySource.years}. Model-based estimates describe county populations, not individual diagnoses, service requests or current capacity. Do not apply them to ZIP areas. Differences do not establish statistical significance or causation.</p>
  </section>;
}
