import {useState,useEffect,useRef} from 'react';
import { Menu, X } from 'lucide-react';
import {SiteFooter} from './SiteFooter.jsx';
import './open-school.css';
const programs=[
{id:'ai',slug:'applied-ai-systems',title:'Applied AI Systems',goal:'I want to build AI systems.',description:'Turn an idea into a working AI system. Test its behavior, identify its limits and explain where a person needs to stay in control.',output:'A bounded AI system, evaluation evidence and an explanation of its limits.',href:'/applied-ai-systems.html'},
{id:'grc',slug:'cybersecurity-grc',title:'Cybersecurity Governance, Risk and Compliance',goal:'I work with risk and controls.',description:'Connect security risks to controls. Check the evidence, identify gaps and recommend what should change. Explain how your conclusions support a security decision.',output:'A risk and control analysis, evidence review and reasoned recommendations.',href:'/cybersecurity-grc.html'},
{id:'iam',slug:'identity-access-management',title:'Identity & Access Management',goal:'I manage identity and access.',description:'Design permissions around real responsibilities. Configure access policies, investigate failures and explain who should have access, why and under what conditions.',output:'An access model, policy configuration and a failure investigation.',href:'/identity-access-management.html'},
{id:'governance',slug:'ai-governance',title:'AI Governance',goal:'I am responsible for AI oversight.',description:'Set responsibilities, assess AI risks and define how decisions should be reviewed. Explain who is accountable and what evidence they need.',output:'An AI governance position covering risk, accountability and review.',href:'/ai-governance.html'}
];
export function SozoRockSchoolHomepage(){
 const [selected,setSelected]=useState(programs[0]);
 const [announcement,setAnnouncement]=useState('');
 const [visited,setVisited]=useState(()=>new Set());
 const [menuOpen,setMenuOpen]=useState(false);
 const nav=useRef(null),menuButton=useRef(null),resultRef=useRef(null),heroRef=useRef(null);
 const [motionEnabled,setMotionEnabled]=useState(false),[heroVisible,setHeroVisible]=useState(true);
 const [reducedMotion,setReducedMotion]=useState(false);
 useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setReducedMotion(query.matches);if(query.matches)setMotionEnabled(false);};update();query.addEventListener('change',update);const observer=new IntersectionObserver(entries=>setHeroVisible(entries[0].isIntersecting));if(heroRef.current)observer.observe(heroRef.current);return()=>{query.removeEventListener('change',update);observer.disconnect();};},[]);
 useEffect(()=>{const initial=programs.find(p=>p.slug===new URLSearchParams(window.location.search).get('program'));if(initial)setSelected(initial);},[]);
 const applyHref='/apply.html?program='+selected.slug;
 const choose=id=>{const p=programs.find(p=>p.id===id);if(!p)return;setSelected(p);setAnnouncement(p.title+' selected. Program details and application links updated.');setVisited(old=>new Set([...old,id]));const url=new URL(window.location.href);url.searchParams.set('program',p.slug);window.history.replaceState(null,'',url.pathname+url.search+url.hash);if(window.innerWidth<=860)requestAnimationFrame(()=>resultRef.current?.scrollIntoView({behavior:reducedMotion?'auto':'smooth',block:'start'}));};
 useEffect(()=>{
  if(!menuOpen)return;
  const before=document.body.style.overflow;document.body.style.overflow='hidden';nav.current?.querySelector('a')?.focus();
  const keydown=e=>{if(e.key==='Escape'){e.preventDefault();setMenuOpen(false);menuButton.current?.focus();}if(e.key==='Tab'){const first=nav.current?.querySelector('a');const last=nav.current?.querySelector('a:last-child');if(!e.shiftKey&&document.activeElement===last){e.preventDefault();menuButton.current?.focus();}else if(e.shiftKey&&document.activeElement===menuButton.current){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===menuButton.current){e.preventDefault();first?.focus();}else if(e.shiftKey&&document.activeElement===first){e.preventDefault();menuButton.current?.focus();}}};
  const resize=()=>{if(window.innerWidth>860)setMenuOpen(false);};
  document.addEventListener('keydown',keydown);window.addEventListener('resize',resize);
  return()=>{document.body.style.overflow=before;document.removeEventListener('keydown',keydown);window.removeEventListener('resize',resize);};
 },[menuOpen]);
 return <div className="home open-school school-ready"><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="nav-shell"><a className="wordmark" href="/" aria-label="SozoRockSchool United States"><span>SozoRockSchool</span><span className="wordmark-country">United States</span></a><nav ref={nav} className="primary-nav" id="primary-nav" aria-label="Primary navigation" data-primary-nav data-open={menuOpen?'':undefined} onClick={()=>setMenuOpen(false)}><a href="#programs">Programs</a><a href="/experience.html">How you learn</a><a href="/enrollment-fees.html">Admissions</a><a className="nav-apply" href={applyHref}>Apply</a></nav><button ref={menuButton} className="menu-toggle" type="button" aria-label={menuOpen?'Close menu':'Open menu'} aria-expanded={menuOpen} aria-controls="primary-nav" data-menu-toggle onClick={()=>setMenuOpen(open=>!open)}>{menuOpen?<X size={22} aria-hidden="true"/>:<Menu size={22} aria-hidden="true"/>}<span>{menuOpen?'Close':'Menu'}</span></button></div></header><main id="main">
<section ref={heroRef} className={"school-hero"+(motionEnabled&&heroVisible&&!reducedMotion?" scene-running":"")} aria-labelledby="hero-title"><picture className="school-hero-art"><source media="(max-width: 860px)" srcSet="/assets/open-school-us-mobile.webp" /><img src="/assets/open-school-us-wide.webp" width="2520" height="1080" alt="" fetchPriority="high" /></picture>
<div className="container school-hero-content"><p className="school-function">AI and cybersecurity Nano-Credentials</p><h1 id="hero-title">Build the technology.<br />Earn the trust.</h1><p className="school-hero-intro">Applied projects. Human assessment.</p><p className="school-facts">12 weeks · 100% virtual · United States<br />3–6 hours/week</p><p className="school-fee">Tuition and enrollment fees will be published before US applications open.</p><div className="school-actions"><a className="school-button school-button-light" data-selected-apply href={applyHref}>Apply</a><a className="school-text-link" href="#programs">Choose your program <span aria-hidden="true">→</span></a></div><p className="school-availability">U.S. applications are not open yet. Check admissions availability before sharing information.</p></div>
{!reducedMotion&&<button type="button" className="scene-motion" data-scene-motion aria-pressed={motionEnabled} onClick={()=>setMotionEnabled(on=>!on)}>{motionEnabled?"Pause scene":"Animate scene"}</button>}<p className="school-scene-caption">Conceptual learning environment. Programs are 100% virtual.</p></section>
<section className="school-programs school-section" id="programs" aria-labelledby="programs-title"><div className="container">
<p className="school-kicker">Programs</p><h2 id="programs-title">Four paths. One school.</h2><p className="school-intro">Choose the responsibility closest to your goals. Each program follows the same twelve-week learning rhythm.</p>
<div className="school-doors" aria-label="Choose a program"><button type="button" className="school-door" data-school-choice="ai" aria-pressed={selected.id==='ai'} onClick={()=>choose('ai')} aria-controls="selected-program"><span className="door-scene scene-ai"><img src="/assets/open-school-us-wide.webp" width="2520" height="1080" loading="lazy" alt="" /></span><span className="door-name">Applied AI Systems</span><span className="door-description">Build and test AI.</span></button><button type="button" className="school-door" data-school-choice="grc" aria-pressed={selected.id==='grc'} onClick={()=>choose('grc')} aria-controls="selected-program"><span className="door-scene scene-grc"><img src="/assets/open-school-us-wide.webp" width="2520" height="1080" loading="lazy" alt="" /></span><span className="door-name">Cybersecurity GRC</span><span className="door-description">Assess security risk.</span></button><button type="button" className="school-door" data-school-choice="iam" aria-pressed={selected.id==='iam'} onClick={()=>choose('iam')} aria-controls="selected-program"><span className="door-scene scene-iam"><img src="/assets/open-school-us-wide.webp" width="2520" height="1080" loading="lazy" alt="" /></span><span className="door-name">Identity &amp; Access Management</span><span className="door-description">Design secure access.</span></button><button type="button" className="school-door" data-school-choice="governance" aria-pressed={selected.id==='governance'} onClick={()=>choose('governance')} aria-controls="selected-program"><span className="door-scene scene-governance"><img src="/assets/open-school-us-wide.webp" width="2520" height="1080" loading="lazy" alt="" /></span><span className="door-name">AI Governance</span><span className="door-description">Guide responsible AI use.</span></button></div>
<div ref={resultRef} className="school-selected" id="selected-program" data-school-result><div><p className="school-kicker">Your program</p><h3 data-school-title>{selected.title}</h3><p className="selected-goal" data-school-goal>{selected.goal}</p><p data-school-description>{selected.description}</p><p><strong>You will develop:</strong> <span data-school-output>{selected.output}</span></p><p className="school-small">Guided practice. Applied project. Human assessment.</p><div className="school-actions"><a className="school-button" data-school-detail href={selected.href}>View program</a><a className="school-text-link" data-school-apply href={applyHref} aria-label={"Apply for "+selected.title}>Apply for this program</a></div></div><p className="school-selected-note">One discipline.<br />Twelve weeks.<br />Your decisions, explained.</p></div>
<p className="visually-hidden" aria-live="polite" data-school-status>{announcement}</p><p className="school-discovery" data-school-discovery hidden={visited.size!==4}>Four entrances. One shared space for learning and human review. That is the idea behind our school sculpture.</p>

</div></section>
<section className="school-rhythm school-section" aria-labelledby="rhythm-title"><div className="container"><p className="school-kicker">How you learn</p><h2 id="rhythm-title">Twelve weeks.<br className="mobile-break" /> A clear progression.</h2><ol className="school-weeks">
<li><span>Week</span><strong>1</strong><h3>Understand</h3><p>Learn the problem, the environment and the standard you are aiming for.</p></li>
<li><span>Week</span><strong>4</strong><h3>Practice</h3><p>Complete guided exercises and explain the choices you make.</p></li>
<li><span>Week</span><strong>8</strong><h3>Apply</h3><p>Develop your project within realistic constraints.</p></li>
<li><span>Week</span><strong>12</strong><h3>Explain and review</h3><p>Present evidence, respond to human review and address required revisions.</p></li></ol><a className="school-text-link" href="/experience.html">How the twelve weeks work <span aria-hidden="true">→</span></a></div></section>
<section className="school-teaching school-section" aria-labelledby="teaching-title"><div className="container school-teaching-layout"><div className="school-teaching-copy"><p className="school-kicker">Our method</p><h2 id="teaching-title">A person assesses<br />your progress.</h2><p>Your final submission is reviewed against the program requirements. You explain your choices and respond to feedback. Attendance alone does not earn a credential.</p><p className="school-director"><strong>Dr. Oluwabiyi Adeyemo</strong><br />Director of Learning, AI &amp; Cybersecurity</p><a className="school-text-link" href="/about.html#director">Meet the director <span aria-hidden="true">→</span></a></div><figure className="school-forum director-photo"><img src="/media/director.webp" width="300" height="360" alt="Dr. Oluwabiyi Adeyemo, Director of Learning, AI and Cybersecurity" loading="lazy" /><figcaption>Dr. Oluwabiyi Adeyemo · Learning leadership</figcaption></figure></div></section>
<section className="school-scope school-section" aria-labelledby="scope-title"><div className="container school-scope-layout"><div><p className="school-kicker">Credentials</p><h2 id="scope-title">A credential with<br />clear limits.</h2><p>Issued only after requirements are met and human authorization is recorded. Each issued credential has a unique verification ID.</p><a className="school-text-link" href="/credential-standards.html">Credential standards and verification <span aria-hidden="true">→</span></a></div><div className="school-scope-note"><p>This is focused professional development.</p><p>It is not a degree, diploma, academic credit, professional license or third-party certification. It does not guarantee a job.</p></div></div></section>
<section className="school-context school-section" aria-labelledby="context-title"><div className="container school-context-layout"><h2 id="context-title">Technical skill<br />includes judgment.</h2><div><p>Building a system is one responsibility. Evaluating risk, controlling access and deciding how it should be used are others.</p><p>The U.S. Bureau of Labor Statistics projects information security analyst employment to grow 21% from 2025 to 2035.</p><p className="school-small">This occupation commonly requires a bachelor’s degree and related experience. This is occupational context, not a claim that a SozoRock credential meets those requirements or produces employment.</p><a className="school-text-link" href="https://www.bls.gov/ooh/computer-and-information-technology/information-security-analysts.htm">Read the BLS occupational outlook <span aria-hidden="true">↗</span></a></div></div></section>
<section className="school-questions school-section" aria-labelledby="questions-title"><div className="container"><p className="school-kicker">Questions</p><h2 id="questions-title">Before you apply.</h2><div className="school-faq">
<details open><summary>What does it cost?</summary><p>The US program is paid professional development. Tuition, enrollment fees and payment dates will be published before applications open. Read the <a href="/enrollment-fees.html">fee and cancellation terms</a> before payment.</p></details>
<details open><summary>How much time will I need?</summary><p>Plan for 3–6 hours each week over twelve weeks. Read the schedule in your offer before accepting your place.</p></details>
<details open><summary>Who is this for?</summary><p>People ready to learn through guided practice, develop an applied project and explain their decisions. Read the entry expectations on your chosen program page.</p></details>
<details><summary>What will the credential mean?</summary><p>It records completion of the stated requirements for one SozoRock Nano-Credential. Issuance requires human assessment and separate authorization.</p></details>
<details><summary>Will it get me a job?</summary><p>No job is guaranteed. You can use your completed project to explain your skills and share verification details of an issued credential.</p></details>
<details><summary>Who is this not for?</summary><p>These programs are not for people seeking a degree, professional license or an automatic certificate for attendance. They require active participation and assessed submissions.</p></details>
</div></div></section>
<section className="school-close school-section" aria-labelledby="close-title"><div className="container"><h2 id="close-title">Choose your program.<br />Check admissions availability.</h2><p>Tuition and enrollment fees will be published before US applications open.</p><a className="school-button school-button-light" data-selected-apply href={applyHref}>Apply</a></div></section>
</main><SiteFooter applyHref={applyHref} /></div>;
}
